export default {
  GET_ERRORS: "GET_ERRORS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GET_PROFILE: "GET_PROFILE",
  PROFILE_LOADING: "PROFILE_LOADING",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  CLEAR_CURRENT_PROFILE: "CLEAR_CURRENT_PROFILE",
  GET_PROFILES: "GET_PROFILES"
};
